[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bc_science_analysis"
version = "0.1.1"
requires-python = ">=3.12"
description = "Scripts for running science analysis on level 1 BlackCAT data."
authors = [
    {name = "Timothy R Emeigh", email = "tre8@psu.edu"}
]
maintainers = [
    {name = "Timothy R Emeigh", email = "tre8@psu.edu"}
]
classifiers = [
]

dependencies = [
    "astropy",
    "bc_caldb @ git+ssh://git@github.com/TimothyRE99/bc_caldb.git",
    "numpy",
    "photutils",
    "reproject",
    "scipy",
]

[project.scripts]
find_peaks = "science_analysis.scripts.find_peaks:main"
image_observation = "science_analysis.scripts.image_observation:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["science_analysis", "science_analysis.*"]
